### ISSUE TITLE
Jenkins no longer supports java 7

### ISSUE THREAD

**Issue by ndelic0** [voxpupuli/puppet-jenkins#638]
On a CentOS6 java class by default installs java-openjdk-1.7.0. That one is no more supported by latest version of Jenkins. The error I'm getting is:
`SEVERE: Failed to initialize Jenkins
java.lang.InternalError
        at sun.security.ec.SunEC.initialize(Native Method)
        at sun.security.ec.SunEC.access$000(SunEC.java:49)
        at sun.security.ec.SunEC$1.run(SunEC.java:61)
        at sun.security.ec.SunEC$1.run(SunEC.java:58)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ec.SunEC.<clinit>(SunEC.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221)
        at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
        at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
        at sun.security.jca.ProviderList.loadAll(ProviderList.java:282)
        at sun.security.jca.ProviderList.removeInvalid(ProviderList.java:299)
        at sun.security.jca.Providers.getFullProviderList(Providers.java:173)
        at java.security.Security.removeProvider(Security.java:444)
        at hudson.WebAppMain.contextInitialized(WebAppMain.java:117)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
`
Issue solved with following:

`class { 'java':
    package => 'java-1.8.0-openjdk-devel',
    before    => Class['jenkins'],
  }
`
 `class { 'jenkins':
    install_java => false,
  }
`

**Comment by jhoblitt** [comment]
This is really an issue with `puppetlabs/java`.  I'm not sure what we can reasonably do other than changing `install_java` to false by default?
